### ISSUE TITLE
Don't make tab/ribbon when receives empty string

### ISSUE THREAD

**Issue by casouri** [tarsius/moody#16]
Since both `""` and `nil` means no information, do you think it's good to make moody behaves in the same way on them?

**Comment by tarsius** [comment]
What part of moody does that and why shouldn't it do that? If you are talking about `moody-wrap`; I think that raises an error of STRING is nil.

**Comment by casouri** [comment]
Oh, I'm sorry, it does raise an exception. I'm thinking about a behavior like 
``` lisp
(moody-wrap "")
=> ""
```

because sometimes I put something like this into mode-line:
``` lisp
(:eval (moody-tab (my-lighter)))
```
and `my-lighter` could return `""` if the major is not applicable.

**Comment by tarsius** [comment]
I think I'll leave it as-is. Maybe I'll change my mind eventually but for now the reasoning is this:

A major motivation for writing this was that `powerline` et al. have colors, directions and what not flip around "randomly", making it very hard to find a certain piece of information by its "usual appearance". It is easier to quickly locate e.g. the third tab when it isn't sometimes the second tab because what would usually be the second tab happens not to be currently displayed because the wrapped value happens to be the empty string right now.

Not saying that it would be completely wrong to do the latter, but for now at least you will have to handle this case explicitly by checking for the empty string yourself before passing the non-empty string, if any, to `moody-wrap`.
