### ISSUE TITLE
Feature Request: Icons support.

### ISSUE THREAD

**Issue by basicfunc** [tarsius/moody#31]
Hey, Dev!
Moody and Minion-mode is perfect combo and I really appreciate your efforts.
I request you to add icon-support for minor modes and evil state, maybe something like this, [Mode-icon](https://github.com/ryuslash/mode-icons/).

**Comment by tarsius** [comment]
In important idea behind these packages is that they only do one thing and can easily be combined with other such packages. So I recommend you just use `mode-icons` to get this behavior. I tried it quickly and it worked for `c-mode`. It didn't work for `elisp-mode` possibly because that now shows either `elisp/d` or `elisp/l` and `mode-icons` doesn't account for that yet.

Anyway, thanks for the suggestion, but the requested functionality is beyond the scope of this package.

**Comment by basicfunc** [comment]
> In important idea behind these packages is that they only do one thing and can easily be combined with other such packages. So I recommend you just use `mode-icons` to get this behavior. I tried it quickly and it worked for `c-mode`. It didn't work for `elisp-mode` possibly because that now shows either `elisp/d` or `elisp/l` and `mode-icons` doesn't account for that yet.
> 
> Anyway, thanks for the suggestion, but the requested functionality is beyond the scope of this package.

Thanks Dev.
Have a nice day.
