### ISSUE TITLE
Moody height differs between Emacs and Emacsclient

### ISSUE THREAD

**Issue by jthaman** [tarsius/moody#32]
I noticed that the height of the Moody modeline depends on how I start my emacs. If I start "Emacs", the height is taller compared to using an emacsclient and then connecting to a server. 

![Screenshot from 2021-09-13 22-13-35](https://user-images.githubusercontent.com/1507619/133183488-6f067b60-1f23-4ec3-8ad7-d1a863264a07.png)

Left is emacsclient, Right is Emacs. My moody configuration is 

```emacs-lisp
(use-package moody
  :straight t
  :after modus-themes
  :custom
  (x-underline-at-descent-line t)
  :config
  (moody-replace-mode-line-buffer-identification))
```
Not really a big deal to me, but I kind of like the slimmer modeline :)

**Comment by tarsius** [comment]
I assume you never get different heights in the same Emacs instance, because if you did, that would would be really weird. You *do* get different heights in these two cases: (1) start Emacs by typing `emacs` into a terminal and (2) starting Emacs in the background by some means like but without that causing an Emacs frame appearing and then later connecting to that by typing `emacsclient` into a terminal.

The reason for the difference is that the height has to be calculated based on some values that are different depending on whether Emacs ever displayed a GUI frame. To ensure the value is always the same, you can set `moody-mode-line-height` explicitly.

**Comment by jthaman** [comment]
Thanks, I'll just explicitly set `moody-mode-line-height` from now on. Why isn't Moody's height simply equal to the height of the built-in mode-line?

**Comment by tarsius** [comment]
I like for it to have a bit of room to breath.
