### ISSUE TITLE
Underline below vc-mode

### ISSUE THREAD

**Issue by memeplex** [tarsius/moody#33]
Hi, am I doing something wrong or is the underline below Git:master in the screenshot something to be expected:

![image](https://user-images.githubusercontent.com/2845433/137093751-1f9ce0fa-5e12-4527-ba91-6377e3330551.png)

If I swap the windows so that the vc-mode indicator is at the bottom of the frame that thin separation disappears, as in the picture in your README. It may be a tiny separator between windows and not part of the modeline itself.

After a quick glance at the code this is the only condition I found that could be related `(window-at-side-p nil 'bottom)`.

**Comment by tarsius** [comment]
This is intentional and accomplished by the condition you located.

`Git:master` is information about the above window. It may or may not also apply to the below window, but if that is so, then that information is being displayed in its own mode-line.

Removing the line would strongly apply the information from the above mode-line applied to the below window.

(Strictly speaking the same applies in the window at the bottom, but since there the only window even further down is the minibuffer, I decided that was okay and opted for what looks better.

**Comment by memeplex** [comment]
I would say that `__/ \___` is either an upward facing tab or two downward facing half-tabs, it's kind of a duck-rabbit situation but I believe that answers the question.

>  Also, can you come up with a better (i.e. unambiguous and short (for use in the first line of a doc-string)) description?

You've lost me here, what doc-string are you referring to?
