### ISSUE TITLE
Symbol’s function definition is void: font-info

### ISSUE THREAD

**Issue by jcs090218** [tarsius/moody#39]
I got the following error in my CI.

```
Symbol’s function definition is void: font-info
```

Can we avoid this by first checking the function's existence before calling it in the root level?

Thanks!

**Comment by tarsius** [comment]
`font-info` is implemented in C and part of Emacs since 2008. It should always be defined.

**Comment by jcs090218** [comment]
The CI test link here, https://github.com/jcs-emacs/jcs-emacs/runs/4819726496?check_suite_focus=true.

It seems like it only happens on the Linux system!

**Comment by tarsius** [comment]
I only took a quick look at that but it seems that you are building your own emacs and while doing so are including some third-party packages. I might be wrong but that was the impression I got.

I know little about how emacs is dumped but from what I understand in a first step a subset of elisp (and apparently c) is loaded and then that is dumped. Then the dumped image is loaded and more stuff is included and then that is dumped again giving us the final emacs image.

It appears to me that you are including some third-party packages in the first dump. You probably shouldn't do that as those packages assume that a fully featured emacs is being used. So my guess is that you can fix this by including third-party packages in the second step instead of the first.

If my speculations are more or less right, then this is not a problem in my package. Packages are allowed to assume that they are being loaded into a fully functional emacs.

**Comment by tarsius** [comment]
Or if you are not dumping your own emacs, then the problem probably is that you are using an emacs without gui support and that such builds do not provide that function. Is that it?

I guess in that case I would suppress the error.

**Comment by jcs090218** [comment]
I have made another quick test here by calling `fboundp` and see if the function exists before installing any package. Here is the test result, https://github.com/jcs-emacs/jcs-emacs/runs/4825073926?check_suite_focus=true. It appears the function cannot be found on `Linux` system but on `Windows`. 😕 


#### 💾  Linux

```
Run make startup
Testing...
[TEST] nil
Debugger entered--Lisp error: (void-function font-info)
...
```

#### 💾 Windows

```
Run make startup
Testing...
[TEST] t
...
```

> I only took a quick look at that but it seems that you are building your own emacs and while doing so are including some third-party packages. I might be wrong but that was the impression I got.

I used [purcell/setup-emacs](https://github.com/purcell/setup-emacs) to get Emacs installed on Linux and macOS. My first impression is the cross-platform issue since it worked on Windows 10, unless the Emacs from [purcell/setup-emacs]() isn't the plain/default one. 

> It appears to me that you are including some third-party packages in the first dump. You probably shouldn't do that as those packages assume that a fully featured emacs is being used. So my guess is that you can fix this by including third-party packages in the second step instead of the first.

Not sure what you mean by, this but isn't function `font-size` from C layer (first dump)?

**Comment by tarsius** [comment]
So then it is probably that:

> Or if you are not dumping your own emacs, then the problem probably is that you are using an emacs without gui support and that such builds do not provide that function. Is that it?
> 
>I guess in that case I would suppress the error.

**Comment by jcs090218** [comment]
I think you are right; windows are gui build.

**Comment by tarsius** [comment]
The description in `xfaces.c` begins with

>    When using Emacs with X, the display style of characters can be
>    changed by defining `faces'.

So...

**Comment by tarsius** [comment]
Fixed as you suggested!

**Comment by jcs090218** [comment]
Thank you! I can fix it in my own CI workflow, but I think it's better to just fix it in the issue package. So other people like myself wouldn't have to deal it! :)
