### ISSUE TITLE
Question about straight.el integration and about autoloads in general

### ISSUE THREAD

**Issue by valignatev** [tarsius/moody#9]
Hi, thanks for your awesome things on emacs!
I've tried to install moody with [straight.el](https://github.com/raxod502/straight.el) and wasn't able to succeed because moody's functions weren't available in my init file's scope. 
Straight's documentation says that it doesn't use `require` and relies on package autoloads instead.
So I've tried explicitly require moody instead like so:
```emacs-lisp
;; the path is where straight clones packages
(require 'moody "~/.emacs.d/straight/repos/moody/moody.el")
```
and it worked.
So here is my question: why it doesn't work with regular straight way? Your other packages (magit and minions) both worked great for me.

P.S. I'm not that experienced in these aspects of emacs, so forgive me if it doesn't make any sense to you :)

**Comment by tarsius** [comment]
> Straight's documentation says that it doesn't use `require` and relies on package autoloads instead.

I think what that means is that it loads `FOO/FOO-autoloads.el` in order to put `FOO/` on the `load-path`.

`moody` currently doesn't define any autoloads - maybe that causes `straight` to forgo creating `moody-autoloads.el`. /cc @raxod502

Whether `moody` should should provide autoloads is another question ... thinking ...

**Comment by tarsius** [comment]
Anyway, the commands are being autoloaded now.

**Comment by raxod502** [comment]
@valignatev Yes, this is expected behavior. `straight.el` does not load a package, it simply makes it available. The same is true for `package.el`. If you wish to use functions from a package, you must `require` it first. For convenience, some packages _autoload_ their functions, so that calling those functions invokes `require` for you. This was previously not the case for this package, so you just had to `require` it first. Whether or not to autoload commands is a subjective concern.

All of the above is assuming that you can use `(require 'moody)` rather than providing the full path as you did in your initial comment. If you can't, then there is a bug in `straight.el`.

@tarsius Yes, if no autoloads are defined, then the autoloads file won't be generated. However, the package should still be added to `load-path`, so I don't think this would produce any unexpected behavior.
